# Generated by Django 6.0.4 on 2026-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['category', 'sort_order', 'name', 'mobile_no', 'membership_no'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='member',
            name='membership_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Membership No'),
        ),
        migrations.AddField(
            model_name='member',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile No'),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('executive', 'Executive Committee'), ('subcommittee', 'Sub Committee')], max_length=50, verbose_name='Category'),
        ),
    ]
