# Generated by Django 6.0.4 on 2026-06-02 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_member_options_member_membership_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room Number')),
            ],
            options={
                'verbose_name': 'Guest Room',
                'verbose_name_plural': 'Guest Rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Department')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('qualifications', models.TextField(blank=True, verbose_name='Qualifications Required')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Application Last Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Visible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='sub_committee_type',
            field=models.CharField(blank=True, choices=[('advisory', 'Advisory Committee'), ('website_edisha', 'Website & e-Disha Committee'), ('infrastructure', 'Infrastructure Committee'), ('finance', 'Finance Committee'), ('technical_chapter', 'Technical Chapter Committee'), ('technical_program_award', 'Technical Program Award Committee'), ('senior_engineer_committee', 'Senior Engineer Committee')], help_text='Only applicable when Category is "Sub Committee"', max_length=50, null=True, verbose_name='Sub Committee Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('executive', 'Executive Committee'), ('subcommittee', 'Sub Committee'), ('senior_members', 'Senior Members')], max_length=50, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='GuestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='Guest Name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('num_people', models.PositiveIntegerField(default=1, verbose_name='Number of Guests')),
                ('check_in', models.DateField(verbose_name='Check-In Date')),
                ('check_out', models.DateField(verbose_name='Check-Out Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='website.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Guest Booking',
                'verbose_name_plural': 'Guest Bookings',
                'ordering': ['-check_in'],
            },
        ),
    ]
