# Generated by Django 6.0.4 on 2026-06-25 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_room_vacancy_member_sub_committee_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['title', 'announcement_date', '-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Announcement Date'),
        ),
    ]
